spring:
  jpa:
    hibernate:
      ddl-auto: none

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_example
    username: root
    password: 123456

  flyway:
    table: flyway_schema_history
    baseline-on-migrate: true


#  spring.jpa.hibernate.ddl-auto= update
#
#  spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/db_example
#
#  spring.datasource.username=root
#
#  spring.datasource.password=123456
#
#  spring.datasource.driver-class-name=com.mysql.jdbc.Driver
# spring.jpa.hibernate.ddl-auto=none
#
#spring.flyway.table=flyway_schema_history


